# ===============================
# Configuración del Servidor
# ===============================
spring.application.name=LearnTrack
server.port=8080

# ===============================
# Conexión a PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/learntrack_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===============================
# Configuración de Hibernate / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Configuración de Mail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=copitocorp.soporte@gmail.com
spring.mail.password=uglw qpni narq hhya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# Configuración de Ollama
# ===============================
spring.ai.openai.base-url=http://ollama:11434
spring.ai.openai.api-key=ollama
spring.ai.openai.chat.options.model=phi3:mini

# ===============================
# Configuración de JWT
# ===============================
jwt.secret=${JWT_SECRET:TuClaveSecretaSuperSeguraParaLearnTrackQueDebeSerLargaChangeInProduction}
jwt.expiration=86400000